import { Switch, switchClasses } from "@mui/material";
import { styled } from "@mui/material/styles";

export const StyledSwitch = styled(Switch)(({ theme, checked }) => ({
  width: "250px",
  height: '55px',
  padding: 8,

  [`& .${switchClasses.root}`]: {
    backgroundColor: "#333",
  },
  [`& .${switchClasses.track}`]: {
    borderRadius: "24px",
    height: '38px',
    backgroundColor: checked ? theme.palette.info.main : "#fff",
    opacity: 1,
    "&:checked": {
      transform: "translateX(168px)",
      opacity: 1,
    },
    "&:before": {
      content: checked ? "'Generated by AI'" : "'Generate by AI'",
      color: checked ? "#fff" : theme.palette.info.main,
      left: 0,
      position: "absolute",
      top: "50%",
      transform: "translateY(-50%)",
      width: '250px',
      textAlign: 'center'
    },

  },
  [`& .${switchClasses.switchBase}`]: {
    "&:checked": {
      transform: "translateX(100px)",
      "&. MuiSwitch-track": {
        backgroundColor: "red"
      } // to jest głupie ale działa
    }
  },
  [`& .${switchClasses.thumb}`]: {
    boxShadow: "none",
    width: 32,
    height: 32,
    margin: 2,
    color: checked ? theme.palette.text.primary : theme.palette.info.main
  },
  [theme.breakpoints.down('laptop')]: {
    width: "160px"
  },
}));
