import { Switch, switchClasses } from "@mui/material";
import { styled } from "@mui/material/styles";

export const StyledSwitch = styled(Switch)(({ theme, checked }) => ({
  width: "250px",
  height: '55px',
  padding: 8,
  [`${theme.breakpoints.down('tablet')}`]: {
    width: '100px',
  },

  [`& .${switchClasses.checked}`]: {
    transform: "translateX(195px)",
    opacity: 1,
    [`${theme.breakpoints.down('tablet')}`]: {
      transform: "translateX(60px)",
    },
    [`& + .${switchClasses.track}`]: {
      backgroundColor: theme.palette.info.main
    }
  },

  [`& .${switchClasses.track}`]: {
    borderRadius: "24px",
    height: '38px',
    backgroundColor: theme.palette.common.white,
    opacity: 1,
    "&:before": {
      content: checked ? "'Generated by AI'" : "'Generate by AI'",
      color: checked ? theme.palette.common.white : theme.palette.info.main,
      left: 0,
      position: "absolute",
      top: "50%",
      transform: "translateY(-50%)",
      width: '250px',
      textAlign: 'center',
      [`${theme.breakpoints.down('tablet')}`]: {
        width: '100px',
        content: "'AI'",
      },
    },
    [`${theme.breakpoints.down('tablet')}`]: {
      height: '32px',
    },
  },
  [`& .${switchClasses.thumb}`]: {
    boxShadow: "none",
    width: 32,
    height: 32,
    margin: 2,
    color: checked ? theme.palette.text.primary : theme.palette.info.main,
    [`${theme.breakpoints.down('tablet')}`]: {
      height: '24px',
      width: '24px'
    },
  },
}));
